server:
    port: 8085

spring:
    application:
        name: auth-service
    profiles:
        active:
        - dev
    security:
        user:
            name: admin
            password: admin123
    data:
        mongodb:
            uri: mongodb://localhost:27017/authdb

eureka:
    client:
        service-url:
            defaultZone: http://admin:admin123@localhost:8761/eureka/        #The defaultZone property specifies the URL of the Eureka server that this instance will communicate with. In this case, it is set to http://admin:admin123@localhost:8761/eureka/, which means that the Eureka server is running on localhost at port 8761, and the username and password for authentication are admin and admin123, respectively.
    instance:
        prefer-ip-address: true

logging:
    level:
        com.tnf.productservice: DEBUG
        org.springframework.cloud.sleuth: DEBUG

jwt:
    secret: TheOneSecretToRuleThemAllSoDoNotTryToGuessIt
    expiration: 86400000
    
management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, prometheus
    metrics:
        tags:
            application: ${spring.application.name}
    tracing:
        enabled: true
        sampling:
            probability: 1.0
        propagation:
            type:
            - B3
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans