# server:
#   port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: product-service
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/api/products/**
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/api/orders/**
      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/api/payments/**
        filters:
          - StripPrefix=1
          - name: CircuitBreaker
            args:
              name: paymentServiceCircuitBreaker
              fallbackUri: forward:/fallback/payments
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, beans, httptrace, gateway
      base-path: /actuator
  
  endpoint:
    health:
      show-details: always
    gateway:
      access: unrestricted

info:
  app:
    name: API Gateway
    description: Manages API gatway
    version: 1.0.0