server:
  port: 9093

spring:
  application:
    name: message-consumer
  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:
      group-id: message-group
      auto-offset-reset: earliest
      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: com.tnf.common_dto.dto.MessageDto
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest