# server:
#     port: 8081

spring:
    application:
        name: product-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/productdb
eureka:
    client:
        service-url:
            defaultZone: http://admin:admin123@localhost:8761/eureka/        #The defaultZone property specifies the URL of the Eureka server that this instance will communicate with. In this case, it is set to http://admin:admin123@localhost:8761/eureka/, which means that the Eureka server is running on localhost at port 8761, and the username and password for authentication are admin and admin123, respectively.
    instance:
        prefer-ip-address: true                       #This property indicates that the service instance should prefer using its IP address over its hostname when registering with Eureka. This can be useful in certain network configurations where the hostname may not be resolvable or may not be the preferred way to access the service.

logging:
    level:
        com.tnf.productservice: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, beans, httptrace
    endpoint:
        health:
            show-details: always

info:
    app:
        name: Product Service
        description: Manages product catalog
        version: 1.0.0